# Generated by Django 2.0 on 2017-12-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264, unique=True)),
                ('publication_date', models.DateTimeField()),
                ('text', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
    ]
